location_name:
  kanto: 関東
  kansai: 関西
  kyushu: 九州

year:
  one: 1年
  two: 2年
  three: 3年
  four: 4年
  five: 5年
  graduate_first: 院1年
  graduate_second: 院2年
  society: 社会人
  teacher: 教員
  other_year: その他

position_name:
  member: メンバー
  leader: リーダー
  pl: プロジェクトリーダー

edupedia_team:
  writer: 取材
  plan: 計画推進
  qm: QM
  bc: BC
  hr: 人事
  account: 会計
  system: システム

roje_project:
  nothing: なし
  vp: VP
  kouko: 高校企画
  tsubomi: つぼみ
  gogatsusai: 五月祭
  vary: VARY
  comp: comp
  kanfo: かんふぉ
  management: 管理課
  pr: 広報課
  account: 会計課
  other: その他

status:
  doing: 進行中
  stagnation: 停滞中
  done: 完了
  planning: 企画中
